### ISSUE TITLE
Missing Migrations

### ISSUE THREAD

**Issue by mogoh** [ketaro/djangocms-rawhtml#2]
I get this error:

> Your models in app(s): 'djangocms_rawhtml' have changes that are not yet reflected in a migration, and so won't be applied.
> Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

**Comment by ketaro** [comment]
Looks like something got updated in Django in the last 5 years.  There's no actual change to the model, probably just the label or something.  Either way, I'll push a new version out with the updated migration.

**Comment by mogoh** [comment]
@ketaro That was quick! Thank you! :smile:
