### ISSUE TITLE
Django 4.2/DjangoCMS 3.11 support

### ISSUE THREAD

**Issue by mogoh** [ketaro/djangocms-rawhtml#4]
- Replace depricated `ugettext` with `gettext`: https://github.com/ketaro/djangocms-rawhtml/pull/3#issue-1763746559
- If I ran `python manage.py makemigrations` after updating to Django 4.2/DjangoCMS 3.11, new migrations will be generated.

**Comment by ketaro** [comment]
Thanks for the heads up.  I haven't updated that far yet, but will take a look.

**Comment by ketaro** [comment]
Release 1.3.0 should address those.  Thanks for the heads up.

**Comment by mogoh** [comment]
Thanks for the fast release.
